version: '3'

services:
    lodex:
        build:
            context: .
        environment:
            http_proxy: ${http_proxy}
            https_proxy: ${https_proxy}
            NODE_OPTIONS: ${NODE_OPTIONS}
            EZMASTER_MONGODB_HOST_PORT: 'mongo:27017'
            EZMASTER_TECHNICAL_NAME: 'lodex'
            no_proxy: 'localhost,127.0.0.1,'
            BABEL_DISABLE_CACHE: 1
        links:
            - mongo
        ports:
            - 3000:3000
    mongo:
        image: mongo:3.4.1
        command: '--smallfiles'
        ports:
            - 27017:27017
